CREATE LOGIN ChuNSLogin
WITH PASSWORD = 'yourStrong(!)Password';

CREATE LOGIN QuanLyLogin
WITH PASSWORD = 'yourStrong(!)Password';

CREATE LOGIN NhanVienLogin
WITH PASSWORD = 'yourStrong(!)Password';

CREATE ROLE ChuNS
CREATE ROLE QuanLy 
CREATE ROLE NhanVien

CREATE USER Dat FOR LOGIN NhanVienLogin
ALTER ROLE NhanVien ADD MEMBER Dat


-- NhanVien
GRANT SELECT, INSERT, UPDATE ON dbo.Sach TO NhanVien
GRANT SELECT, INSERT, UPDATE ON dbo.NhaXuatBan TO NhanVien
GRANT SELECT, INSERT, UPDATE ON dbo.TheLoai TO NhanVien
GRANT SELECT, INSERT, UPDATE ON dbo.TacGia TO NhanVien
GRANT SELECT ON dbo.NhanSu TO NhanVien
GRANT SELECT ON dbo.ChucVu TO NhanVien
GRANT SELECT, INSERT, UPDATE ON dbo.KhachHang TO NhanVien
GRANT SELECT, INSERT, UPDATE ON dbo.LichSuTinhNo TO NhanVien
GRANT SELECT, INSERT, UPDATE ON dbo.HoaDon TO NhanVien
GRANT SELECT, INSERT, UPDATE ON dbo.ChiTietHoaDon TO NhanVien

DENY DELETE ON dbo.Sach TO NhanVien
DENY DELETE ON dbo.NhaXuatBan TO NhanVien
DENY DELETE ON dbo.TheLoai TO NhanVien
DENY DELETE ON dbo.TacGia TO NhanVien
DENY DELETE ON dbo.NhanSu TO NhanVien
DENY DELETE ON dbo.ChucVu TO NhanVien
DENY DELETE ON dbo.KhachHang TO NhanVien
DENY DELETE ON dbo.KhachHang TO NhanVien
DENY DELETE ON dbo.LichSuTinhNo TO NhanVien
DENY DELETE ON dbo.HoaDon TO NhanVien
DENY DELETE ON dbo.ChiTietHoaDon TO NhanVien


-- QuanLy
GRANT SELECT, INSERT, UPDATE ON dbo.Sach TO QuanLy
GRANT SELECT, INSERT, UPDATE ON dbo.NhaXuatBan TO QuanLy
GRANT SELECT, INSERT, UPDATE ON dbo.TheLoai TO QuanLy
GRANT SELECT, INSERT, UPDATE ON dbo.TacGia TO QuanLy
GRANT SELECT, INSERT, UPDATE ON dbo.NhanSu TO QuanLy
GRANT SELECT ON dbo.ChucVu TO QuanLy
GRANT SELECT, INSERT, UPDATE ON dbo.ChiTietHoaDon TO QuanLy
GRANT SELECT, INSERT, UPDATE ON dbo.LichSuTinhNo TO QuanLy
GRANT SELECT, INSERT, UPDATE ON dbo.HoaDon TO QuanLy
GRANT SELECT, INSERT, UPDATE ON dbo.ChiTietHoaDon TO QuanLy
GRANT SELECT, INSERT, UPDATE ON dbo.ChiTietHoaDon TO QuanLy

GRANT DELETE ON dbo.Sach TO QuanLy
GRANT DELETE ON dbo.NhaXuatBan TO QuanLy
GRANT DELETE ON dbo.TheLoai TO QuanLy
GRANT DELETE ON dbo.TacGia TO QuanLy
GRANT DELETE ON dbo.NhanSu TO QuanLy
GRANT DELETE ON dbo.ChucVu TO QuanLy
GRANT DELETE ON dbo.ChiTietHoaDon TO QuanLy
GRANT DELETE ON dbo.LichSuTinhNo TO QuanLy
GRANT DELETE ON dbo.HoaDon TO QuanLy
GRANT DELETE ON dbo.ChiTietHoaDon TO QuanLy
GRANT DELETE ON dbo.ChiTietHoaDon TO QuanLy


-- ChuNS
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.Sach TO ChuNS
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.NhaXuatBan TO ChuNS
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.TheLoai TO ChuNS
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.TacGia TO ChuNS
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.NhanSu TO ChuNS
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.ChucVu TO ChuNS
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.ChiTietHoaDon TO ChuNS
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.LichSuTinhNo TO ChuNS
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.HoaDon TO ChuNS
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.ChiTietHoaDon TO ChuNS
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.ChiTietHoaDon TO ChuNS