CREATE OR ALTER PROCEDURE uspDropAllTables
AS BEGIN 
	DECLARE @sql NVARCHAR(max)=''

	SELECT @sql += ' Drop table ' + QUOTENAME(TABLE_SCHEMA) + '.'+ QUOTENAME(TABLE_NAME) + '; '
	FROM   INFORMATION_SCHEMA.TABLES
	WHERE  TABLE_TYPE = 'BASE TABLE'
	
	Exec Sp_executesql @sql
END
GO


CREATE OR ALTER PROCEDURE uspCreateTables
AS BEGIN 
	CREATE TABLE CaiDatRangBuoc
	(
		MinSoLuongNhap INT NOT NULL,
		MaxTonTruocNhap INT NOT NULL,
		MinTonSauBan INT NOT NULL,
		GiaBanTrenGiaNhap FLOAT NOT NULL,
		MaxTienNo DECIMAL(19, 4) NOT NULL,
		ThuQuaTienNo BIT NOT NULL
	)
	
	
	CREATE TABLE Sach
	(
	    ID    	INT IDENTITY(1, 1) PRIMARY KEY,
	    TenSach    	NVARCHAR(80) NOT NULL ,
	    GiaNhap    	DECIMAL(19, 4) NOT NULL,
	    SoTrang 	INT,
	    IDNhaXuatBan 	INT NOT NULL,
	)
	
	CREATE TABLE NhaXuatBan
	(
		ID INT IDENTITY(1, 1) PRIMARY KEY,
		TenNXB NVARCHAR(30) NOT NULL,
		SDT VARCHAR(11),
		Email VARCHAR(30),
		INDEX IX_NhaXuatBan UNIQUE NONCLUSTERED (Email)
		WHERE Email IS NOT NULL
	)
	
	CREATE TABLE LichSuNhapBan
	(
	    ID    INT IDENTITY(1, 1) PRIMARY KEY,
	    ThoiDiem    DATETIME NOT NULL UNIQUE,
	)
	
	CREATE TABLE Sach_LichSuNhapBan
	(
		IDLichSu    INT NOT NULL,
	    IDSach    INT NOT NULL,
	    TonTruoc    INT NOT NULL,
	    SoLuong    INT NOT NULL,
		Gia		DECIMAL(19, 4) NOT NULL,
	    CONSTRAINT PK_IDSach_IDLichSu PRIMARY KEY (IDSach,IDLichSu)
	) 
	
	CREATE TABLE TheLoai
	(
	    ID    INT IDENTITY(1, 1) PRIMARY KEY,
	    TenTheLoai    NVARCHAR(30) NOT NULL UNIQUE
	)
	
	CREATE TABLE TheLoai_Sach
	(
	    IDTheLoai    INT NOT NULL,
	    IDSach    INT NOT NULL,
	    CONSTRAINT PK_IDSach_IDTheLoai PRIMARY KEY (IDSach,IDTheLoai)
	)
	
	CREATE TABLE TacGia
	(
		ID INT IDENTITY(1, 1) PRIMARY KEY,
		HoTen NVARCHAR(50) NOT NULL,
		Email VARCHAR(30),
		INDEX IX_TacGia UNIQUE NONCLUSTERED (Email)
		WHERE Email IS NOT NULL,
	)
	
	CREATE TABLE TacGia_Sach
	(
		IDTacGia 	INT NOT NULL,
		IDSach	INT NOT NULL,
		CONSTRAINT PK_IDSach_IDTacGia PRIMARY KEY (IDSach,IDTacGia),
	)
	
	CREATE TABLE ChucVu
	(
	    ID    INT IDENTITY(1, 1) PRIMARY KEY,
	    TenChucVu    NVARCHAR(30) NOT NULL
	)
	
	CREATE TABLE NhanSu
	(
	    ID    INT IDENTITY(1, 1) PRIMARY KEY,
	    Hoten    NVARCHAR(50) NOT NULL,
		DiaChi    NVARCHAR(50) NOT NULL,
	    SDT    VARCHAR(11) NOT NULL UNIQUE,
		Email    VARCHAR(30) NOT NULL UNIQUE,
		IDChucVu INT NOT NULL
	)
	
	CREATE TABLE KhachHang
	(
	    ID    INT IDENTITY(1, 1) PRIMARY KEY,
	    Hoten    NVARCHAR(50) NOT NULL,
		DiaChi    NVARCHAR(30) NOT NULL,
	    SDT    VARCHAR(11) NOT NULL UNIQUE,
		Email    VARCHAR(30) NOT NULL UNIQUE
	)
	
	CREATE TABLE LichSuTinhNo
	(
	    ID    INT IDENTITY(1, 1) PRIMARY KEY,
		IDKhachHang INT NOT NULL,
		ThoiDiem DATETIME NOT NULL UNIQUE,
		TongNoTruoc DECIMAL(19, 4) NOT NULL,
		SoTien DECIMAL(19, 4) NOT NULL
	)
	
	CREATE TABLE HoaDon
	(
	    ID    INT IDENTITY(1, 1) PRIMARY KEY,
	    SoTienTra    NVARCHAR(30) NOT NULL,
	    IDLichSu    INT NOT NULL,
	    IDNhanVienThanhToan  INT NOT NULL,
		IDKhachHang INT NOT NULL
	)
	
	CREATE TABLE ChiTietHoaDon
	(
		IDSach  INT NOT NULL,
		IDHoaDon INT NOT NULL,
		SoLuong INT NOT NULL,
		GiaSach DECIMAL(19, 4) NOT NULL
	)
END
GO


CREATE OR ALTER PROCEDURE uspApplyConstraints
AS BEGIN 
	ALTER TABLE Sach
	ADD CONSTRAINT FK_NhaXuatBan__NXB FOREIGN KEY (IDNhaXuatBan) REFERENCES NhaXuatBan(ID)
	
	ALTER TABLE Sach_LichSuNhapBan
	ADD CONSTRAINT FK_Sach_LichSuNhapBan__Sach FOREIGN KEY (IDSach)  REFERENCES Sach(ID),
		CONSTRAINT FK_Sach_LichSuNhapBan__LichSu FOREIGN KEY (IDLichSu)  REFERENCES LichSuNhapBan(ID)
	
	ALTER TABLE TheLoai_Sach
	ADD CONSTRAINT FK_TheLoai_Sach__Sach  FOREIGN KEY (IDSach)  REFERENCES Sach(ID),
		CONSTRAINT FK_TheLoai_Sach__TheLoai  FOREIGN KEY (IDTheLoai)  REFERENCES TheLoai(ID)
		
	ALTER TABLE TacGia_Sach
	ADD CONSTRAINT FK_TacGia_Sach__Sach  FOREIGN KEY (IDSach)  REFERENCES Sach(ID),
		CONSTRAINT FK_TacGia_Sach__TacGia  FOREIGN KEY (IDTacGia)  REFERENCES TacGia(ID)
	
	ALTER TABLE NhanSu
	ADD CONSTRAINT FK_NhanSu__CapBac  FOREIGN KEY (IDChucVu)  REFERENCES ChucVu(ID)
	
	ALTER TABLE LichSuTinhNo
	ADD CONSTRAINT FK_LichSuTinhNo__KhachHang  FOREIGN KEY (IDKhachHang)  REFERENCES KhachHang(ID)
	
	ALTER TABLE HoaDon
	ADD CONSTRAINT FK_HoaDon__NhanSu  FOREIGN KEY (IDNhanVienThanhToan)  REFERENCES NhanSu(ID),
		CONSTRAINT FK_HoaDon__KhachHang  FOREIGN KEY (IDKhachHang)  REFERENCES KhachHang(ID),
		CONSTRAINT FK_HoaDon_LichSuNhapBan FOREIGN KEY (IDLichSu)  REFERENCES LichSuNhapBan(ID)
	
	ALTER TABLE ChiTietHoaDon
	ADD CONSTRAINT FK_ChiTietHD__Sach  FOREIGN KEY (IDSach)  REFERENCES Sach(ID),
		CONSTRAINT FK_ChiTietHD__HoaDon  FOREIGN KEY (IDHoaDon)  REFERENCES HoaDon(ID)
END
GO